--- #YAML:1.0
name:                IPC-Cmd
version:             0.44
abstract:            A cross platform way of running (interactive) commandline programs.
license:             ~
author:              
    - Jos Boumans <kane[at]cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Locale::Maketext::Simple:      0
    Module::Load::Conditional:     0
    Params::Check:                 0.20
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
