# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         IPC-Cmd
version:      0.41_04
version_from: lib/IPC/Cmd.pm
installdirs:  site
requires:
    Locale::Maketext::Simple:      0
    Module::Load::Conditional:     0
    Params::Check:                 0.20
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
